### ISSUE TITLE
Migrate versions declaration to manifest files 

### ISSUE THREAD

**Issue by cbeauchesne** [DataDog/system-tests#1571]
* [x] cpp #1559
* [x] .NET #1570 
* [x] golang #1563 
* [x] nodejs #1549
* [x] java #1587
* [x] php_appsec #1582 
* [x] php #1585
* [x] python #1576
* [x] ruby #1572
* [x] agent #1591
* [x] Do a final pass for leftovers #1591
* [x] update the doc #1592
* [x] Remove the temporary code for migration #1594
